spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

testify:
  containers:
    enabled: false  # Using H2 in-memory database for demo
  database:
    columnNamingStrategy: caseInsensitive

logging:
  level:
    com.github.loadup.testify: DEBUG
    org.springframework.jdbc: DEBUG
